export default (constant = {
  DETAIL: 'Detail',
  CATEGORY: 'Category',
  STRING: 'string',
  INT: 'int',
  BOOLEAN: 'bool',
  ID: 'id',
  CHILDCATEGORY: 'ChildCategory',
  ANSWER: 'Answer',
  TRANSCRIPT: 'Transcript',
  LESSON: 'Lesson',
  QUESTION: 'Question',
  NEWWORD: 'NewWord',
  ASYN_LANGUAGE: '@language',
  SettingScreen: {
    ENGLISH_VALUE: 'en',
    VIETNAM_VALUE: 'vi',
    VIETNAM_LABEL: 'Việt Nam',
    ENGLISH_LABEL: 'English',
    LANGUAGE: 'Language',
    CANCEL: 'Cancel'
  },
  USE_FOR_ME: 'boolstringintenglish',
  RELOAD_LISTWORD: 'reloadListWord',
  RELOAD_LISTWRONGWORD: 'reloadListWrongWord',
  RELOAD_LANGUAGE: 'reloadLanguage',
  ISFIRST: 'firstTime',
  STATUS_NETWORK: 'statusNetwork',
  BACK_HANDLE: 'backHandle',
  STORAGE_REGISTER_NOTIFICATION: '@tpro_english_register_notification',
  PUSH_NOTIFICATION_STATUS: '@tpro_english_PUSH_NOTIFICATION_STATUS',
  PUSH_NOTIFICATION_TIME: '@tpro_english_PUSH_NOTIFICATION_TIME',
  NOTIFICATION_INFOR: {
    ID: 'NotificationID_Tpro_English',
    TITLE: 'Tpro English',
    CONTENT:
      'Hãy học tiếng anh và làm chủ cuộc đời mình nào bạn trẻ.',
  },
  CHANNEL_OBJECT: {
    channelId: 'TproEnglishChannelID',
    channelName: 'TproEnglishChannelName',
    channelDes: 'TproEnglishChannelDes',
  },
});
